image:
    - Visual Studio 2015
    - Visual Studio 2017
    - Visual Studio 2019    

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\comms_champion
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

matrix:
    environment:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
    exclude:
        - image: Visual Studio 2015
          CPP_STD: 17        
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cd build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DCC_QT_DIR=%QTDIR% -DCMAKE_CXX_STANDARD=%CPP_STD% -DCMAKE_INSTALL_PREFIX=%cd%/install -DCC_ENABLE_DEMO_PROTOCOL=ON
    - nmake install
    - IF "%CONFIGURATION%"=="Release" ( nmake deploy_qt )
test_script:
    - ctest 


