dist: trusty
language: cpp
sudo: true
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7    
      env: _CC=gcc-4.7 _CXX=g++-4.7 _BUILD="-DCC_COMMS_LIB_ONLY=ON"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7    
      env: _CC=gcc-4.7 _CXX=g++-4.7 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=Release"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7    
      env: _CC=gcc-4.7 _CXX=g++-4.7 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=MinSizeRel"  
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8    
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8    
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=Release"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8    
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=MinSizeRel"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      env: _CC=gcc-4.9 _CXX=g++-4.9 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      env: _CC=gcc-4.9 _CXX=g++-4.9 _BUILD="-DCMAKE_BUILD_TYPE=Release"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      env: _CC=gcc-4.9 _CXX=g++-4.9 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel"      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5    
      env: _CC=gcc-5 _CXX=g++-5 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"     
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel          
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 -DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6    
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel          
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 -DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7    
      env: _CC=gcc-7 _CXX=g++-7 _BUILD=-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8  
      env: _CC=clang-3.8 _CXX=clang++-3.8 _BUILD="-DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8  
      env: _CC=clang-3.8 _CXX=clang++-3.8 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8  
      env: _CC=clang-3.8 _CXX=clang++-3.8 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"            
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9    
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9    
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9    
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0    
      env: _CC=clang-4.0 _CXX=clang++-4.0 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0    
      env: _CC=clang-4.0 _CXX=clang++-4.0 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0    
      env: _CC=clang-4.0 _CXX=clang++-4.0 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0   
      env: _CC=clang-5.0 _CXX=clang++-5.0 
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _BUILD="-DCMAKE_BUILD_TYPE=Release"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0    
      env: _CC=clang-5.0 _CXX=clang++-5.0 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"
      
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -q
  - sudo apt-get install libc++-dev cmake cmake-data qt56base qt56serialport -y      

before_script:
  - mkdir build
  - cd build
  - source /opt/qt56/bin/qt56-env.sh
  - CC=${_CC} CXX=${_CXX} cmake .. ${_BUILD}

script:
  - VERBOSE=1 make install
  - ctest

